name: Build Willy for T-Embed CC1101
on: [workflow_dispatch, push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with: { python-version: "3.11" }
      - name: Install PlatformIO
        run: pip install platformio
      - name: Apply T-Embed config
        run: |
          mkdir -p boards
          cat > boards/t_embed_cc1101.h <<'EOF'
          // LILYGO T-Embed CC1101 pins (from LilyGO ref)
          #define BOARD_USER_KEY 6
          #define BOARD_PWR_EN   15
          #define WS2812_NUM_LEDS 8
          #define WS2812_DATA_PIN 14
          #define BOARD_IR_EN 2
          #define BOARD_IR_RX 1
          #define BOARD_MIC_DATA 42
          #define BOARD_MIC_CLK  39
          #define BOARD_VOICE_BCLK  46
          #define BOARD_VOICE_LRCLK 40
          #define BOARD_VOICE_DIN   7
          #define DISPLAY_WIDTH  170
          #define DISPLAY_HEIGHT 320
          #define DISPLAY_BL   21
          #define DISPLAY_CS   41
          #define DISPLAY_MISO -1
          #define DISPLAY_MOSI  9
          #define DISPLAY_SCLK 11
          #define DISPLAY_DC   16
          #define DISPLAY_RST  40
          #define ENCODER_INA 4
          #define ENCODER_INB 5
          #define ENCODER_KEY 0
          #define BOARD_I2C_SDA  8
          #define BOARD_I2C_SCL  18
          #define BOARD_PN532_RF_REST 45
          #define BOARD_PN532_IRQ     17
          #define BOARD_SPI_SCK  11
          #define BOARD_SPI_MOSI 9
          #define BOARD_SPI_MISO 10
          #define BOARD_SD_CS   13
          #define BOARD_LORA_CS   12
          #define BOARD_LORA_IO2  38
          #define BOARD_LORA_IO0  3
          #define BOARD_LORA_SW1  47
          #define BOARD_LORA_SW0  48
          EOF
      - name: Build
        env:
          PLATFORMIO_BUILD_FLAGS: >
            -DARDUINO_USB_MODE=1 -DARDUINO_USB_CDC_ON_BOOT=1
            -DBOARD_TEMBED_CC1101
        run: |
          pio run -e esp32s3_usb_16MB
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: willy_t-embed_cc1101_bin
          path: .pio/build/esp32s3_usb_16MB/firmware.bin
